FROM golang:alpine

RUN apk add --no-cache nodejs make curl curl-dev git

RUN npm install -g eslint

RUN go get -u github.com/golang/lint/golint

RUN curl https://glide.sh/get | sh

COPY . /go/src/app

WORKDIR /go/src/app

RUN make install

RUN NODE_ENV=production make build




